sr =  (input("Enter the student roll number"))
sn =  (input("Enter the student name"))
m=int(input("Enter math marks :"))
p=int(input("Enter physics marks :"))
c=int(input("Enter chem marks :"))
print("student roll number:",sr)
print("student name:",sn)
print("math marks:",m)
print("physics marks:",p)
print("chemistry marks",c)
print("Total marks : ",m+p+c)
print("Average markes :",round(((m+p+c)/3),2))
